services:
    webservice:
        image: crccheck/hello-world
        ports:
          - 8000

    proxy:
        image: nginx:stable-bullseye
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./certbot/challenge:/data/certbot-challenge:ro
            - ./certbot/certificates:/data/certificates:ro

    certbot:
        image: certbot/certbot:v2.5.0
        volumes: 
            - ./certbot/certificates:/etc/letsencrypt
            - ./certbot/challenge:/data-www-challenge
        # command: certonly --webroot -w /data-www-challenge --force-renewal --email {email} -d {domain} --agree-tos
